export const CATEGORIES = [
  { id: 'nurse', name: 'Hamshira', icon: '👩‍⚕️' },
  { id: 'pedagogue', name: 'Pedagog', icon: '👨‍🏫' },
  { id: 'educator', name: 'Tarbiyachi', icon: '🧑‍🏫' },
  { id: 'preschool_education', name: 'Maktabgacha taʼlim', icon: '🧸' },
  { id: 'music_education', name: 'Musiqa taʼlimi', icon: '🎵' },
  { id: 'physical_education', name: 'Jismoniy tarbiya', icon: '🏃' },
  { id: 'medical_nursing', name: 'Tibbiy hamshiralik', icon: '🩺' },
  { id: 'midwifery', name: 'Akusherlik', icon: '🤰' },
  { id: 'pharmacy', name: 'Farmatsiya', icon: '💊' },
  { id: 'lab_diagnostics', name: 'Laboratoriya diagnostikasi', icon: '🔬' },
  { id: 'software_engineering', name: 'Dasturiy injiniring', icon: '💻' },
  { id: 'computer_engineering', name: 'Kompyuter injiniringi', icon: '🖥️' },
  { id: 'information_technology', name: 'Axborot texnologiyalari', icon: '🌐' },
  { id: 'electrical_engineering', name: 'Elektrotexnika', icon: '⚡' },
  { id: 'auto_service', name: 'Avtomobillarga texnik xizmat koʻrsatish', icon: '🔧' },
  { id: 'auto_repair', name: 'Avtomobillarni taʼmirlash', icon: '🚗' },
  { id: 'construction', name: 'Qurilish', icon: '🏗️' },
  { id: 'architecture', name: 'Arxitektura', icon: '📐' },
  { id: 'geodesy', name: 'Geodeziya', icon: '🧭' },
  { id: 'land_management', name: 'Yer tuzish', icon: '🗺️' },
  { id: 'agriculture', name: 'Qishloq xoʻjaligi', icon: '🌾' },
  { id: 'agronomy', name: 'Agronomiya', icon: '🌱' },
  { id: 'veterinary', name: 'Veterinariya', icon: '🐾' },
  { id: 'food_technology', name: 'Oziq-ovqat texnologiyasi', icon: '🍲' },
  { id: 'sewing_technology', name: 'Tikuvchilik texnologiyasi', icon: '🧵' },
  { id: 'textile_technology', name: 'Toʻqimachilik texnologiyasi', icon: '🧶' },
  { id: 'design', name: 'Dizayn', icon: '🎨' },
  { id: 'cosmetology', name: 'Kosmetologiya', icon: '💄' },
  { id: 'hairdressing', name: 'Sartaroshlik', icon: '💇' },
  { id: 'cooking', name: 'Oshpazlik', icon: '🍳' },
  { id: 'confectionery_craft', name: 'Qandolatchilik', icon: '🧁' },
  { id: 'hospitality', name: 'Mehmonxona xoʻjaligi', icon: '🏨' },
  { id: 'tourism', name: 'Turizm', icon: '✈️' },
  { id: 'trade', name: 'Savdo ishi', icon: '🛒' },
  { id: 'human_resources', name: 'Kadrlar ishi', icon: '👔' },
  { id: 'law', name: 'Huquqshunoslik', icon: '⚖️' },
  { id: 'social_work', name: 'Ijtimoiy ish', icon: '🫶' },
  { id: 'librarianship', name: 'Kutubxonachilik', icon: '📚' },
  { id: 'archiving', name: 'Arxiv ishi', icon: '🗄️' },
  { id: 'printing', name: 'Poligrafiya', icon: '🖨️' },
  { id: 'metal_chasing', name: 'Zarbgarlik', icon: '🔨' },
  { id: 'embroidery', name: 'Kashtachilik', icon: '🪡' },
  { id: 'pottery', name: 'Kulolchilik', icon: '🏺' },
  { id: 'carpet_weaving', name: 'Gilamchilik', icon: '🧿' },
  { id: 'other', name: 'Boshqa', icon: '✨' }
];

export const SKILLS = [
  { id: "house_cleaning", name: "Uy tozalash" },
  { id: "cooking", name: "Ovqat pishirish" },
  { id: "sewing", name: "Tikuvchilik" },
  { id: "babysitting", name: "Bolalarga qarash" },
  { id: "english", name: "Ingliz tili" },
  { id: "russian", name: "Rus tili" },
  { id: "math", name: "Matematika" },
  { id: "makeup", name: "Makiyaj" },
  { id: "manicure", name: "Manikyur" },
  { id: "knitting", name: "Toʻqish" },
  { id: "confectionery", name: "Qandolatpazlik" }
];
