import { profileCompletionPercent } from '../common/profile-completion.util';
import { formatExportValue, riskIndex } from '../common/xlsx-safe.util';

export type ExportColumn = { header: string; key: string; width: number };

export const USER_EXPORT_COLUMNS: ExportColumn[] = [
  { header: 'UID', key: 'uid', width: 26 },
  { header: 'Ism', key: 'firstName', width: 16 },
  { header: 'Familiya', key: 'lastName', width: 16 },
  { header: "To'liq ism", key: 'fullName', width: 24 },
  { header: 'Rol', key: 'role', width: 14 },
  { header: 'Profil %', key: 'completion', width: 10 },
  { header: 'Email', key: 'email', width: 28 },
  { header: 'Telefon', key: 'phoneNumber', width: 18 },
  { header: 'Telegram', key: 'telegram', width: 18 },
  { header: 'Telegram tasdiq', key: 'telegramVerified', width: 14 },
  { header: 'Viloyat', key: 'region', width: 18 },
  { header: 'Tuman', key: 'district', width: 18 },
  { header: 'Mahalla', key: 'neighborhood', width: 18 },
  { header: 'Kasb', key: 'profession', width: 20 },
  { header: "Ta'lim darajasi", key: 'educationLevel', width: 16 },
  { header: 'Ko‘nikmalar', key: 'skills', width: 28 },
  { header: 'Tillar', key: 'languages', width: 20 },
  { header: 'Bio', key: 'bio', width: 32 },
  { header: 'Kasbiy qisqa', key: 'professionalSummary', width: 32 },
  { header: 'Aloqa usuli', key: 'preferredContact', width: 16 },
  { header: 'Tajriba darajasi', key: 'experienceLevel', width: 16 },
  { header: 'Bandlik', key: 'availability', width: 14 },
  { header: 'Ish qidiryapti', key: 'lookingForWork', width: 14 },
  { header: 'Ta’lim', key: 'education', width: 28 },
  { header: 'Tajriba', key: 'experience', width: 28 },
  { header: 'Sertifikatlar', key: 'certificates', width: 24 },
  { header: 'Portfolio', key: 'portfolio', width: 24 },
  { header: 'Rezyume shablon', key: 'resumeTemplate', width: 16 },
  { header: 'Tashkilot', key: 'companyName', width: 22 },
  { header: 'Biznes turi', key: 'businessType', width: 16 },
  { header: 'Soha', key: 'industry', width: 16 },
  { header: "Ro'yxat raqami", key: 'registrationNumber', width: 18 },
  { header: 'STIR', key: 'tin', width: 16 },
  { header: 'Sayt', key: 'website', width: 22 },
  { header: 'Tashkil etilgan yil', key: 'foundedYear', width: 14 },
  { header: 'Xodimlar soni', key: 'employeeCount', width: 14 },
  { header: 'Ofis manzili', key: 'officeAddress', width: 28 },
  { header: 'Galereya', key: 'companyGallery', width: 24 },
  { header: 'Tashkilot hujjatlari', key: 'companyDocuments', width: 24 },
  { header: 'Aloqa shaxslari', key: 'recruiterContacts', width: 24 },
  { header: 'Profil rasmi', key: 'photoUrl', width: 28 },
  { header: 'Muqova', key: 'coverUrl', width: 28 },
  { header: 'Joylashuv ulashilgan', key: 'locationSharingEnabled', width: 16 },
  { header: 'Kenglik', key: 'latitude', width: 12 },
  { header: 'Uzunlik', key: 'longitude', width: 12 },
  { header: 'Joylashuv yangilangan', key: 'locationUpdatedAt', width: 20 },
  { header: 'Tasdiqlangan', key: 'isVerified', width: 12 },
  { header: 'Tekshiruv holati', key: 'verificationStatus', width: 16 },
  { header: 'Premium', key: 'isPremium', width: 10 },
  { header: 'Reyting', key: 'rating', width: 10 },
  { header: 'Sharhlar', key: 'reviewCount', width: 10 },
  { header: 'Yakunlangan ishlar', key: 'completedJobs', width: 14 },
  { header: 'Bloklangan', key: 'isBlocked', width: 12 },
  { header: 'Blok sababi', key: 'blockReason', width: 24 },
  { header: 'Bloklangan sana', key: 'blockedAt', width: 20 },
  { header: 'Blok muddati', key: 'blockUntil', width: 20 },
  { header: 'Ishonch bali', key: 'trustScore', width: 12 },
  { header: 'Xulq belgilari', key: 'behaviorFlags', width: 20 },
  { header: 'Qoidabuzarlik', key: 'violationCount', width: 12 },
  { header: 'Risk ball', key: 'riskScore', width: 10 },
  { header: 'Oxirgi qoidabuzarlik', key: 'lastViolation', width: 20 },
  { header: 'Yaratilgan', key: 'createdAt', width: 20 },
  { header: 'Yangilangan', key: 'updatedAt', width: 20 },
  { header: 'Oxirgi faollik', key: 'lastActive', width: 20 },
  { header: "Shaxsiy to'liq ism", key: 'pi_fullName', width: 22 },
  { header: "Tug'ilgan sana", key: 'pi_dateOfBirth', width: 14 },
  { header: 'Yosh', key: 'pi_age', width: 8 },
  { header: 'Jinsi', key: 'pi_gender', width: 10 },
  { header: 'Oilaviy holati', key: 'pi_maritalStatus', width: 14 },
  { header: 'Farzandlar', key: 'pi_childrenStatus', width: 12 },
  { header: 'Farzandlar soni', key: 'pi_childrenCount', width: 12 },
  { header: 'Shaxsiy kasb', key: 'pi_profession', width: 16 },
  { header: 'Mutaxassislik', key: 'pi_specialty', width: 16 },
  { header: "Shaxsiy ta'lim", key: 'pi_educationLevel', width: 16 },
  { header: 'Millati', key: 'pi_nationality', width: 14 },
  { header: 'Fuqarolik', key: 'pi_citizenship', width: 14 },
  { header: 'Joriy manzil', key: 'pi_currentAddress', width: 24 },
  { header: 'Doimiy manzil', key: 'pi_permanentAddress', width: 24 },
  { header: 'Shaxsiy telefon', key: 'pi_phone', width: 16 },
  { header: "Qo'shimcha telefon", key: 'pi_additionalPhone', width: 16 },
  { header: 'Shaxsiy email', key: 'pi_email', width: 22 },
  { header: 'O‘zi haqida', key: 'pi_about', width: 28 },
  { header: 'Izoh', key: 'pi_notes', width: 24 },
  { header: "Qo'shimcha shaxsiy", key: 'pi_extra', width: 28 },
  { header: 'Oila daromadi', key: 'ci_familyIncome', width: 16 },
  { header: 'Ona ijtimoiy holati', key: 'ci_motherSocialStatus', width: 18 },
  { header: "Ta'lim natijalari", key: 'ci_educationResults', width: 16 },
  { header: 'Davomat', key: 'ci_attendance', width: 12 },
  { header: 'Salomatlik', key: 'ci_healthStatus', width: 14 },
  { header: 'Psixologik holat', key: 'ci_psychologicalState', width: 16 },
  { header: 'Nogironlik', key: 'ci_disabilityStatus', width: 14 },
  { header: 'Erta nikoh xavfi', key: 'ci_earlyMarriageRisk', width: 14 },
  { header: "Zo'ravonlik xavfi", key: 'ci_violenceRisk', width: 14 },
  { header: 'Raqamli savodxonlik', key: 'ci_digitalLiteracy', width: 16 },
  { header: 'Xavf bahosi', key: 'ci_riskAssessment', width: 24 },
  { header: 'Risk indeksi', key: 'ci_riskIndex', width: 12 },
  { header: "Qo'shimcha indikator", key: 'ci_extra', width: 24 },
  { header: 'Pasport holati', key: 'v_status', width: 14 },
  { header: 'Hujjat turi', key: 'v_documentType', width: 14 },
  { header: 'Pasport seriyasi', key: 'v_series', width: 12 },
  { header: 'Pasport raqami', key: 'v_number', width: 14 },
  { header: 'JShShIR', key: 'v_pinfl', width: 18 },
  { header: 'Pasportdagi ism', key: 'v_fullName', width: 22 },
  { header: 'ID hujjat havolasi', key: 'v_idPhotoUrl', width: 32 },
  { header: 'Selfi havolasi', key: 'v_selfieUrl', width: 32 },
  { header: 'Tekshiruv sanasi', key: 'v_createdAt', width: 20 },
  { header: 'Rad sababi', key: 'v_rejectionReason', width: 24 },
  { header: 'Tekshiruv izohi', key: 'v_reviewNote', width: 24 },
];

const PERSONAL_KEYS = [
  'fullName',
  'dateOfBirth',
  'age',
  'gender',
  'maritalStatus',
  'childrenStatus',
  'childrenCount',
  'profession',
  'specialty',
  'educationLevel',
  'nationality',
  'citizenship',
  'currentAddress',
  'permanentAddress',
  'phone',
  'additionalPhone',
  'email',
  'about',
  'notes',
] as const;

const INDICATOR_KEYS = [
  'familyIncome',
  'motherSocialStatus',
  'educationResults',
  'attendance',
  'healthStatus',
  'psychologicalState',
  'disabilityStatus',
  'earlyMarriageRisk',
  'violenceRisk',
  'digitalLiteracy',
  'riskAssessment',
] as const;

function asRecord(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
  return value as Record<string, unknown>;
}

function extras(record: Record<string, unknown>, known: readonly string[]): Record<string, unknown> {
  const skip = new Set<string>(known);
  const extra: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (skip.has(key) || value == null || value === '') continue;
    extra[key] = value;
  }
  return extra;
}

export function buildUserExportRow(
  user: Record<string, unknown>,
  verification?: Record<string, unknown> | null,
): Record<string, string | number> {
  const pi = asRecord(user.personalInfo);
  const ci = asRecord(user.coreIndicators);
  const passport = asRecord(verification?.passportData);
  const cell = (value: unknown) => formatExportValue(value);

  return {
    uid: cell(user.id),
    firstName: cell(user.firstName),
    lastName: cell(user.lastName),
    fullName: cell(user.fullName),
    role: cell(user.role),
    completion: profileCompletionPercent(user),
    email: cell(user.email),
    phoneNumber: cell(user.phoneNumber),
    telegram: cell(user.telegram),
    telegramVerified: cell(user.telegramVerified),
    region: cell(user.region),
    district: cell(user.district),
    neighborhood: cell(user.neighborhood),
    profession: cell(user.profession),
    educationLevel: cell(user.educationLevel),
    skills: cell(user.skills),
    languages: cell(user.languages),
    bio: cell(user.bio),
    professionalSummary: cell(user.professionalSummary),
    preferredContact: cell(user.preferredContact),
    experienceLevel: cell(user.experienceLevel),
    availability: cell(user.availability),
    lookingForWork: cell(user.lookingForWork),
    education: cell(user.education),
    experience: cell(user.experience),
    certificates: cell(user.certificates),
    portfolio: cell(user.portfolio),
    resumeTemplate: cell(user.resumeTemplate),
    companyName: cell(user.companyName),
    businessType: cell(user.businessType),
    industry: cell(user.industry),
    registrationNumber: cell(user.registrationNumber),
    tin: cell(user.tin),
    website: cell(user.website),
    foundedYear: cell(user.foundedYear),
    employeeCount: cell(user.employeeCount),
    officeAddress: cell(user.officeAddress),
    companyGallery: cell(user.companyGallery),
    companyDocuments: cell(user.companyDocuments),
    recruiterContacts: cell(user.recruiterContacts),
    photoUrl: cell(user.photoUrl),
    coverUrl: cell(user.coverUrl),
    locationSharingEnabled: cell(user.locationSharingEnabled),
    latitude: cell(user.latitude),
    longitude: cell(user.longitude),
    locationUpdatedAt: cell(user.locationUpdatedAt),
    isVerified: cell(user.isVerified),
    verificationStatus: cell(user.verificationStatus),
    isPremium: cell(user.isPremium),
    rating: cell(user.rating),
    reviewCount: cell(user.reviewCount),
    completedJobs: cell(user.completedJobs),
    isBlocked: cell(user.isBlocked),
    blockReason: cell(user.blockReason),
    blockedAt: cell(user.blockedAt),
    blockUntil: cell(user.blockUntil),
    trustScore: cell(user.trustScore),
    behaviorFlags: cell(user.behaviorFlags),
    violationCount: cell(user.violationCount),
    riskScore: cell(user.riskScore),
    lastViolation: cell(user.lastViolation),
    createdAt: cell(user.createdAt),
    updatedAt: cell(user.updatedAt),
    lastActive: cell(user.lastActive),
    pi_fullName: cell(pi.fullName),
    pi_dateOfBirth: cell(pi.dateOfBirth),
    pi_age: cell(pi.age),
    pi_gender: cell(pi.gender),
    pi_maritalStatus: cell(pi.maritalStatus),
    pi_childrenStatus: cell(pi.childrenStatus),
    pi_childrenCount: cell(pi.childrenCount),
    pi_profession: cell(pi.profession),
    pi_specialty: cell(pi.specialty),
    pi_educationLevel: cell(pi.educationLevel),
    pi_nationality: cell(pi.nationality),
    pi_citizenship: cell(pi.citizenship),
    pi_currentAddress: cell(pi.currentAddress),
    pi_permanentAddress: cell(pi.permanentAddress),
    pi_phone: cell(pi.phone),
    pi_additionalPhone: cell(pi.additionalPhone),
    pi_email: cell(pi.email),
    pi_about: cell(pi.about),
    pi_notes: cell(pi.notes),
    pi_extra: cell(extras(pi, [...PERSONAL_KEYS, 'updatedAt', 'updatedBy', 'updatedByRole'])),
    ci_familyIncome: cell(ci.familyIncome),
    ci_motherSocialStatus: cell(ci.motherSocialStatus),
    ci_educationResults: cell(ci.educationResults),
    ci_attendance: cell(ci.attendance),
    ci_healthStatus: cell(ci.healthStatus),
    ci_psychologicalState: cell(ci.psychologicalState),
    ci_disabilityStatus: cell(ci.disabilityStatus),
    ci_earlyMarriageRisk: cell(ci.earlyMarriageRisk),
    ci_violenceRisk: cell(ci.violenceRisk),
    ci_digitalLiteracy: cell(ci.digitalLiteracy),
    ci_riskAssessment: cell(ci.riskAssessment),
    ci_riskIndex: riskIndex(ci),
    ci_extra: cell(extras(ci, INDICATOR_KEYS)),
    v_status: cell(verification?.status),
    v_documentType: cell(verification?.documentType),
    v_series: cell(passport.series),
    v_number: cell(passport.number),
    v_pinfl: cell(passport.pinfl),
    v_fullName: cell(passport.fullName),
    v_idPhotoUrl: cell(verification?.idPhotoUrl || verification?.documentUrl),
    v_selfieUrl: cell(verification?.selfieUrl),
    v_createdAt: cell(verification?.createdAt),
    v_rejectionReason: cell(verification?.rejectionReason),
    v_reviewNote: cell(verification?.reviewNote),
  };
}
